[general]
shell = "zsh"
shell_options = ""

[keymap]
timemachine_go_to_past = "Shift-Down"
timemachine_go_to_more_past = "Ctrl-Down"
timemachine_go_to_future = "Shift-Up"
timemachine_go_to_more_future = "Ctrl-Up"
timemachine_go_to_now = "Ctrl-Shift-Up"
timemachine_go_to_oldest = "Ctrl-Shift-Down"